### ISSUE TITLE
Missing implementation for CGMDisplay#drawCallback

### ISSUE THREAD

**Issue by daviddiana11** [jpprade/jcgmtosvg#1]
Hi @jpprade, 
Thanks for this nice extension to jcgm-core! I am giving it a try and could not find the `CGMDisplay#drawCallback` method in your jcgm-core fork.
Therefore, may you please update your jcgm-core fork accordingly, so it is compatible with your latest jcgmtosvg version? 

Cheers,
David

**Comment by jpprade** [comment]
Yes sure let me check, maybe I haven't pushed everything

**Comment by jpprade** [comment]
ok I see drawCallback() is a method that I added to my jcgm-core fork. 
It is not present in the main lib, only in my fork, so you won't be able to use jcgmtosvg with the main lib.

I did it because the main PolyBezier was not giving me accurate drawing and I extended it inPolyBezierV2.

**Comment by jpprade** [comment]
and yes I have not pushed last version I doing it

**Comment by jpprade** [comment]
Try to switch to the "evol" branch and the method will be present

**Comment by daviddiana11** [comment]
Appreciate your quick feedback Jean-Philippe :)

I can't see the "evol" branch, only the main one.
Is this "evol" branch another private clone repo of the main, or is it just not pushed yet?

**Comment by jpprade** [comment]
It a branch on the jcgm-core fork : 
https://github.com/jpprade/jcgm-core/branches

I pushed it a few minutes ago

**Comment by daviddiana11** [comment]
Found it, thank you!
FYI there should be a 2.0.0 version of [jcgm-core](https://github.com/SwissAS/jcgm-core) released very soon. It will contain some of the commands you implemented, plus the required changes to make it compatible with your extension.
